# Generated by Django 6.0.4 on 2026-04-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1_session_key', models.CharField(max_length=40)),
                ('participant2_session_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершён')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_delete_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='SecretWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'secret_weight',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_session_key', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_session_key', models.CharField(max_length=40)),
                ('encrypted_text', models.TextField()),
                ('encryption_key', models.CharField(max_length=44)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_count', models.IntegerField(default=0)),
                ('exchange', models.ForeignKey(blank=True, db_column='exchange_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.exchange')),
                ('weight', models.ForeignKey(db_column='weight_id', on_delete=django.db.models.deletion.PROTECT, to='exchange.secretweight')),
            ],
            options={
                'db_table': 'secret',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.secret')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
